### PR TITLE
Spelling Fix

### PR DESCRIPTION
**Pull request by parrker**
Hi, 

Saw your post on Reddit, I think this is a cool little side project, especially as it's in TypeScript. I would like to help you a bit with bugs and improvements, when I can.

This is just the most obvious little thing that I noticed, but I'll try to be of more help later.

### CODE REVIEW

**Comment by mikehadlow** [comment]
First pull-request! Excellent! Many thanks for this! The spelling correction is very much appreciated, I'll happily merge that commit. I'm not so sure about the upper-lower case of the roman numerals - see my comment on the issue.

If you can submit these two commits as two separate PRs, I'll merge the spelling correction right away, and let's talk about the roman numeral capitalisation.

**Comment by parrker** [comment]
Hi Mike, thanks for fast reply. 

I wasn't sure how to split one pull request into two, so I just made one more commit reverting the changes made for capitalising major chords numerals.

Is this okay?

**Comment by mikehadlow** [comment]
Yes, that's fine. You'll still need to merge master though, because I've made some commits since you forked. BTW, sorry about all this, I hope it's not putting you off because I really do appreciate the contribution.

**Comment by parrker** [comment]
Okay, looks better now. 

It's my first pull request in a long time, I'm sorry it takes me so long to do everything.

**Comment by mikehadlow** [comment]
Great, all looks good. Many thanks for this!

**Pull request merged**
