### PR TITLE
make it easier to contribute and try gtr-cof from sources

### PR DESCRIPTION
**Pull request by akosyakov**
To try:
gtr-cof

In order to try it yourself with a fork: https://gitpod.io#https://github.com/akosyakov/gtr-cof

To contribute:
gtr-cof-pr

### CODE REVIEW

**Comment by mikehadlow** [comment]
Hmm, not sure about this. It looks somewhat like a commercial for a paid product?

**Comment by akosyakov** [comment]
Hi @mikehadlow :wave: Sorry, if it looked like an advertisement and not giving any explanation.

A product is called Gitpod. It's a VS Code-powered IDE and a cloud-based Linux container configured specifically for the project at hand. We've launched a public beta about 3 weeks ago and it's free to use now. You can learn more about it in [this announcement](https://medium.com/gitpod/gitpod-gitpod-online-ide-for-github-6296b907a886).

I've come across your project because it was trending on GitHub another day and looked pretty cool. Since it's based on similar technologies as Gitpod, e.g. TypeScript and Node.js, it should be a perfect fit. 

Regarding PR: [.gitpod](https://github.com/mikehadlow/gtr-cof/pull/33/files#diff-2cf2dd26e5640af9877cc099e05c1288) is a configuration file specifying which ports should be exposed and startup commands. Gitpod can be started by prefixing any GitHub URL with `gitpod.io#`, for this PR: 
https://gitpod.io#https://github.com/mikehadlow/gtr-cof/pull/33

I'm trying to learn what preventing developers like you from signing up and using Gitpod. We will be glad to any feedback. Also if you need to know something else to consider it, please let me know!

We are monitoring user issues [here](https://github.com/gitpod-io/gitpod). If you decide to give it a shot, I can also monitor your repo to take care of any issues regarding developing in Gitpod.

**Comment by mikehadlow** [comment]
Hi Anton,

It looks like a really cool tool and I appreciate you bringing it to my
attention. It'd be great if you are successful with it.

However, if you see it from my point of view. If I accepted commits from
everyone who had some kind of tooling start up, my code would be littered
with config files that I, and most other people probably wouldn't care
about, and that would be bad. So sorry, as I said I wish you the very best
of luck, but I'm not going to accept this PR.

Best regards,
Mike

**Comment by akosyakov** [comment]
> However, if you see it from my point of view. If I accepted commits from
everyone who had some kind of tooling start up, my code would be littered
with config files that I, and most other people probably wouldn't care
about, and that would be bad.

Thank you for feedback. Makes sense. If someone is interested there is https://github.com/gitpod-io/definitely-gp to add the configuration externally.

**Pull request closed without merging**
